[database]
name = "mysql"
url = "boot_demo_rw:5c9C27omdA!d%^8v@(localhost:3306)/boot-demo?charset=utf8&parseTime=true"
singular-table = true
debug-mode = true
max-idle-conns = 10
max-open-conns = 10

[server]
context-path = "gin-demo"
port = "8004"
log-path = "logs"
gin-mode = "release"
